"""Import all normalizer classes for `main()` registry wiring."""

from __future__ import annotations

from warlock.normalizers.abnormal_security import AbnormalSecurityNormalizer
from warlock.normalizers.accessowl import AccessOwlNormalizer
from warlock.normalizers.addigy import AddigyNormalizer
from warlock.normalizers.adp import ADPNormalizer
from warlock.normalizers.aikido import AikidoNormalizer
from warlock.normalizers.aircall import AircallNormalizer
from warlock.normalizers.akamai import AkamaiNormalizer
from warlock.normalizers.alibaba import AlibabaNormalizer
from warlock.normalizers.ansible import AnsibleNormalizer
from warlock.normalizers.anthropic_platform import AnthropicPlatformNormalizer
from warlock.normalizers.appomni import AppOmniNormalizer
from warlock.normalizers.archer import ArcherNormalizer
from warlock.normalizers.argocd import ArgoCDNormalizer
from warlock.normalizers.arnica import ArnicaNormalizer
from warlock.normalizers.arthur_ai import ArthurAINormalizer
from warlock.normalizers.asana import AsanaNormalizer
from warlock.normalizers.ashby import AshbyNormalizer
from warlock.normalizers.attio import AttioNormalizer
from warlock.normalizers.automox import AutomoxNormalizer
from warlock.normalizers.awarego import AwareGONormalizer
from warlock.normalizers.aws import AWSNormalizer
from warlock.normalizers.aws_acm import AwsAcmNormalizer
from warlock.normalizers.aws_backup import AWSBackupNormalizer
from warlock.normalizers.aws_bedrock import AWSBedrockNormalizer
from warlock.normalizers.aws_codecommit import AWSCodeCommitNormalizer
from warlock.normalizers.aws_govcloud import AWSGovCloudNormalizer
from warlock.normalizers.aws_inspector import AWSInspectorNormalizer
from warlock.normalizers.aws_secrets import AwsSecretsNormalizer
from warlock.normalizers.axonius import AxoniusNormalizer
from warlock.normalizers.azure import AzureNormalizer
from warlock.normalizers.azure_devops import AzureDevOpsNormalizer
from warlock.normalizers.azure_keyvault import AzureKeyVaultNormalizer
from warlock.normalizers.azure_repos import AzureReposNormalizer
from warlock.normalizers.backstage import BackstageNormalizer
from warlock.normalizers.bamboohr import BambooHRNormalizer
from warlock.normalizers.banyan import BanyanNormalizer
from warlock.normalizers.barracuda import BarracudaNormalizer
from warlock.normalizers.base import NormalizerRegistry
from warlock.normalizers.basecamp import BasecampNormalizer
from warlock.normalizers.bigeye import BigeyeNormalizer
from warlock.normalizers.bigid import BigIDNormalizer
from warlock.normalizers.bitbucket import BitbucketNormalizer
from warlock.normalizers.bitwarden import BitwardenNormalizer
from warlock.normalizers.boundary import BoundaryNormalizer
from warlock.normalizers.box import BoxNormalizer
from warlock.normalizers.brex import BrexNormalizer
from warlock.normalizers.bugcrowd import BugcrowdNormalizer
from warlock.normalizers.buildkite import BuildkiteNormalizer
from warlock.normalizers.canva import CanvaNormalizer
from warlock.normalizers.certn import CertnNormalizer
from warlock.normalizers.chainguard import ChainguardNormalizer
from warlock.normalizers.checkmarx import CheckmarxNormalizer
from warlock.normalizers.checkr import CheckrNormalizer
from warlock.normalizers.cisco_umbrella import CiscoUmbrellaNormalizer
from warlock.normalizers.clickup import ClickUpNormalizer
from warlock.normalizers.close_crm import CloseCRMNormalizer
from warlock.normalizers.cloudflare import CloudflareNormalizer
from warlock.normalizers.cloudhealth import CloudHealthNormalizer
from warlock.normalizers.cobalt import CobaltNormalizer
from warlock.normalizers.code42 import Code42Normalizer
from warlock.normalizers.cohesity import CohesityNormalizer
from warlock.normalizers.commvault import CommvaultNormalizer
from warlock.normalizers.conductorone import ConductorOneNormalizer
from warlock.normalizers.confluence import ConfluenceNormalizer
from warlock.normalizers.contentful import ContentfulNormalizer
from warlock.normalizers.cookiebot import CookiebotNormalizer
from warlock.normalizers.copper import CopperNormalizer
from warlock.normalizers.cornerstone import CornerstoneNormalizer
from warlock.normalizers.coursera import CourseraNormalizer
from warlock.normalizers.credo_ai import CredoAINormalizer
from warlock.normalizers.crowdstrike import CrowdStrikeNormalizer
from warlock.normalizers.crowdstrike_spotlight import CrowdStrikeSpotlightNormalizer
from warlock.normalizers.cyberark import CyberArkNormalizer
from warlock.normalizers.cybeready import CyberReadyNormalizer
from warlock.normalizers.cyral import CyralNormalizer
from warlock.normalizers.dashlane import DashlaneNormalizer
from warlock.normalizers.datadog import DatadogNormalizer
from warlock.normalizers.dayforce import DayforceNormalizer
from warlock.normalizers.dbt_labs import DbtLabsNormalizer
from warlock.normalizers.deel import DeelNormalizer
from warlock.normalizers.defender import DefenderNormalizer
from warlock.normalizers.dialpad import DialpadNormalizer
from warlock.normalizers.digicert import DigiCertNormalizer
from warlock.normalizers.digitalocean import DigitalOceanNormalizer
from warlock.normalizers.docebo import DoceboNormalizer
from warlock.normalizers.docusign import DocuSignNormalizer
from warlock.normalizers.domo import DomoNormalizer
from warlock.normalizers.doppler import DopplerNormalizer
from warlock.normalizers.drata import DrataNormalizer
from warlock.normalizers.drata_api import DrataApiNormalizer
from warlock.normalizers.dropbox import DropboxNormalizer
from warlock.normalizers.dropbox_sign import DropboxSignNormalizer
from warlock.normalizers.druva import DruvaNormalizer
from warlock.normalizers.duo import DuoNormalizer
from warlock.normalizers.dynatrace import DynatraceNormalizer
from warlock.normalizers.easyllama import EasyLlamaNormalizer
from warlock.normalizers.egnyte import EgnyteNormalizer
from warlock.normalizers.eight_x_eight import EightByEightNormalizer
from warlock.normalizers.elastic import ElasticNormalizer
from warlock.normalizers.employment_hero import EmploymentHeroNormalizer
from warlock.normalizers.entra_id import EntraIDNormalizer
from warlock.normalizers.envoy import EnvoyNormalizer
from warlock.normalizers.ermetic import ErmeticNormalizer
from warlock.normalizers.f5 import F5Normalizer
from warlock.normalizers.fiddler_ai import FiddlerAINormalizer
from warlock.normalizers.fifteenfive import FifteenFiveNormalizer
from warlock.normalizers.firehydrant import FireHydrantNormalizer
from warlock.normalizers.fivetran import FivetranNormalizer
from warlock.normalizers.fleet import FleetNormalizer
from warlock.normalizers.fortinet import FortinetNormalizer
from warlock.normalizers.fortytwoCrunch import FortyTwoCrunchNormalizer
from warlock.normalizers.fossa import FossaNormalizer
from warlock.normalizers.freshdesk import FreshdeskNormalizer
from warlock.normalizers.freshsales import FreshsalesNormalizer
from warlock.normalizers.freshservice import FreshserviceNormalizer
from warlock.normalizers.gcp import GCPNormalizer
from warlock.normalizers.gcp_secrets import GcpSecretsNormalizer
from warlock.normalizers.generic import GenericNormalizer
from warlock.normalizers.github import GitHubNormalizer
from warlock.normalizers.go1 import GO1Normalizer
from warlock.normalizers.gong import GongNormalizer
from warlock.normalizers.google_drive import GoogleDriveNormalizer
from warlock.normalizers.greenhouse import GreenhouseNormalizer
from warlock.normalizers.guardduty import GuardDutyNormalizer
from warlock.normalizers.hackerone import HackerOneNormalizer
from warlock.normalizers.halo_security import HaloSecurityNormalizer
from warlock.normalizers.harness import HarnessNormalizer
from warlock.normalizers.height import HeightNormalizer

# --- New normalizers (186 expansion) ---
from warlock.normalizers.heroku import HerokuNormalizer
from warlock.normalizers.hetzner import HetznerNormalizer
from warlock.normalizers.hexnode import HexnodeNormalizer
from warlock.normalizers.hibob import HiBobNormalizer
from warlock.normalizers.hireright import HireRightNormalizer
from warlock.normalizers.horizon3 import Horizon3Normalizer
from warlock.normalizers.hr_cloud import HRCloudNormalizer
from warlock.normalizers.huawei import HuaweiNormalizer
from warlock.normalizers.hubspot import HubSpotNormalizer
from warlock.normalizers.humaans import HumaansNormalizer
from warlock.normalizers.huntress import HuntressNormalizer
from warlock.normalizers.ibm_cloud import IBMCloudNormalizer
from warlock.normalizers.immuta import ImmutaNormalizer
from warlock.normalizers.imperva import ImpervaNormalizer
from warlock.normalizers.incident_io import IncidentIONormalizer
from warlock.normalizers.indent import IndentNormalizer
from warlock.normalizers.infisical import InfisicalNormalizer
from warlock.normalizers.infosec_iq import InfosecIQNormalizer
from warlock.normalizers.infracost import InfracostNormalizer
from warlock.normalizers.intercom import IntercomNormalizer
from warlock.normalizers.intigriti import IntigritiNormalizer
from warlock.normalizers.intune import IntuneNormalizer
from warlock.normalizers.ironclad import IroncladNormalizer
from warlock.normalizers.isolved import ISolvedNormalizer
from warlock.normalizers.ivanti import IvantiNormalizer
from warlock.normalizers.ivanti_patch import IvantiPatchNormalizer
from warlock.normalizers.jamf import JamfNormalizer
from warlock.normalizers.jetbrains import JetBrainsNormalizer
from warlock.normalizers.jit_security import JitSecurityNormalizer
from warlock.normalizers.justworks import JustworksNormalizer
from warlock.normalizers.keeper import KeeperNormalizer
from warlock.normalizers.kenjo import KenjoNormalizer
from warlock.normalizers.ketch import KetchNormalizer
from warlock.normalizers.knowbe4 import KnowBe4Normalizer
from warlock.normalizers.kolide import KolideNormalizer
from warlock.normalizers.kubecost import KubecostNormalizer
from warlock.normalizers.kubernetes import KubernetesNormalizer
from warlock.normalizers.lacework import LaceworkNormalizer
from warlock.normalizers.lastpass import LastPassNormalizer
from warlock.normalizers.lattice import LatticeNormalizer
from warlock.normalizers.launchdarkly import LaunchDarklyNormalizer
from warlock.normalizers.leapsome import LeapsomeNormalizer
from warlock.normalizers.lever import LeverNormalizer
from warlock.normalizers.linear import LinearNormalizer
from warlock.normalizers.linkedin_learning import LinkedInLearningNormalizer
from warlock.normalizers.linode import LinodeNormalizer
from warlock.normalizers.logrhythm import LogRhythmNormalizer
from warlock.normalizers.manageengine import ManageEngineNormalizer
from warlock.normalizers.microsoft_teams import MicrosoftTeamsNormalizer
from warlock.normalizers.mimecast import MimecastNormalizer
from warlock.normalizers.miradore import MiradoreNormalizer
from warlock.normalizers.miro import MiroNormalizer
from warlock.normalizers.mixpanel import MixpanelNormalizer
from warlock.normalizers.mlflow import MLflowNormalizer
from warlock.normalizers.monday import MondayNormalizer
from warlock.normalizers.mongodb_atlas import MongoDBAtlasNormalizer
from warlock.normalizers.monte_carlo import MonteCarloNormalizer
from warlock.normalizers.moxso import MoxsoNormalizer
from warlock.normalizers.namely import NamelyNormalizer
from warlock.normalizers.nessus import NessusNormalizer
from warlock.normalizers.netlify import NetlifyNormalizer
from warlock.normalizers.netskope import NetskopeNormalizer
from warlock.normalizers.netsuite import NetSuiteNormalizer
from warlock.normalizers.newrelic import NewRelicNormalizer
from warlock.normalizers.nightfall import NightfallNormalizer
from warlock.normalizers.ninjaone import NinjaOneNormalizer
from warlock.normalizers.noname import NonameNormalizer
from warlock.normalizers.nordpass import NordPassNormalizer
from warlock.normalizers.notion import NotionNormalizer
from warlock.normalizers.nudge_security import NudgeSecurityNormalizer
from warlock.normalizers.obsidian_security import ObsidianSecurityNormalizer
from warlock.normalizers.oci import OCINormalizer
from warlock.normalizers.okta import OktaNormalizer
from warlock.normalizers.onelogin import OneLoginNormalizer
from warlock.normalizers.onepassword import OnePasswordNormalizer
from warlock.normalizers.onetrust import OneTrustNormalizer
from warlock.normalizers.oomnitza import OomnitzaNormalizer
from warlock.normalizers.openai_platform import OpenAIPlatformNormalizer
from warlock.normalizers.openvpn import OpenVPNNormalizer
from warlock.normalizers.opsgenie import OpsgenieNormalizer
from warlock.normalizers.oracle_hcm import OracleHCMNormalizer
from warlock.normalizers.orca import OrcaNormalizer
from warlock.normalizers.osano import OsanoNormalizer
from warlock.normalizers.ovh import OVHNormalizer

# --- New normalizers (84) ---
from warlock.normalizers.pagerduty import PagerDutyNormalizer
from warlock.normalizers.palo_alto import PaloAltoNormalizer
from warlock.normalizers.patch_mgmt_microsoft import MicrosoftPatchMgmtNormalizer
from warlock.normalizers.paychex_flex import PaychexFlexNormalizer
from warlock.normalizers.paylocity import PaylocityNormalizer
from warlock.normalizers.pentera import PenteraNormalizer
from warlock.normalizers.personio import PersonioNormalizer
from warlock.normalizers.ping_identity import PingIdentityNormalizer
from warlock.normalizers.ping_identity_new import PingIdentityNewNormalizer
from warlock.normalizers.pipedrive import PipedriveNormalizer
from warlock.normalizers.plextrac import PlexTracNormalizer
from warlock.normalizers.prisma import PrismaNormalizer
from warlock.normalizers.proofpoint import ProofpointNormalizer
from warlock.normalizers.purview import PurviewNormalizer
from warlock.normalizers.qlik import QlikNormalizer
from warlock.normalizers.qualys import QualysNormalizer
from warlock.normalizers.ramp import RampNormalizer
from warlock.normalizers.rapid7 import Rapid7Normalizer
from warlock.normalizers.render import RenderNormalizer
from warlock.normalizers.retool import RetoolNormalizer
from warlock.normalizers.ringcentral import RingCentralNormalizer
from warlock.normalizers.rollbar import RollbarNormalizer
from warlock.normalizers.rootly import RootlyNormalizer
from warlock.normalizers.rubrik import RubrikNormalizer
from warlock.normalizers.rubrik_security import RubrikSecurityNormalizer
from warlock.normalizers.runzero import RunZeroNormalizer
from warlock.normalizers.sailpoint import SailPointNormalizer
from warlock.normalizers.salesforce import SalesforceNormalizer
from warlock.normalizers.salt_security import SaltSecurityNormalizer
from warlock.normalizers.sap_successfactors import SAPSuccessFactorsNormalizer
from warlock.normalizers.saviynt import SaviyntNormalizer
from warlock.normalizers.scaleway import ScalewayNormalizer
from warlock.normalizers.secureframe import SecureframeNormalizer
from warlock.normalizers.securityscorecard import SecurityScorecardNormalizer
from warlock.normalizers.segment import SegmentNormalizer
from warlock.normalizers.sendgrid import SendGridNormalizer
from warlock.normalizers.sentinel import SentinelNormalizer
from warlock.normalizers.sentinelone import SentinelOneNormalizer
from warlock.normalizers.sentry import SentryNormalizer
from warlock.normalizers.servicenow import ServiceNowNormalizer
from warlock.normalizers.servicenow_cmdb import ServiceNowCMDBNormalizer
from warlock.normalizers.servicenow_grc import ServiceNowGRCNormalizer
from warlock.normalizers.servicenow_itam import ServiceNowITAMNormalizer
from warlock.normalizers.shortcut import ShortcutNormalizer
from warlock.normalizers.sigma_computing import SigmaComputingNormalizer
from warlock.normalizers.smarsh import SmarshNormalizer
from warlock.normalizers.smartrecruiters import SmartRecruitersNormalizer
from warlock.normalizers.smartsheet import SmartsheetNormalizer
from warlock.normalizers.snipe_it import SnipeITNormalizer
from warlock.normalizers.snowflake import SnowflakeNormalizer
from warlock.normalizers.snyk import SnykNormalizer
from warlock.normalizers.snyk_container import SnykContainerNormalizer
from warlock.normalizers.socketdev import SocketdevNormalizer
from warlock.normalizers.sonarcloud import SonarCloudNormalizer
from warlock.normalizers.sonarqube import SonarQubeNormalizer
from warlock.normalizers.sophos import SophosNormalizer
from warlock.normalizers.sosafe import SoSafeNormalizer
from warlock.normalizers.splunk import SplunkNormalizer
from warlock.normalizers.spot_netapp import SpotNetAppNormalizer
from warlock.normalizers.spotio import SpotioNormalizer
from warlock.normalizers.sprinto import SprintoNormalizer
from warlock.normalizers.sterling import SterlingNormalizer
from warlock.normalizers.strongdm import StrongDMNormalizer
from warlock.normalizers.sumo_logic import SumoLogicNormalizer
from warlock.normalizers.sumo_logic_new import SumoLogicNewNormalizer
from warlock.normalizers.supabase import SupabaseNormalizer
from warlock.normalizers.syft_grype import SyftGrypeNormalizer
from warlock.normalizers.tableau import TableauNormalizer
from warlock.normalizers.tailscale import TailscaleNormalizer
from warlock.normalizers.talentlms import TalentLMSNormalizer
from warlock.normalizers.tanium import TaniumNormalizer
from warlock.normalizers.teams_compliance import TeamsComplianceNormalizer
from warlock.normalizers.teamtailor import TeamtailorNormalizer
from warlock.normalizers.teamviewer import TeamViewerNormalizer
from warlock.normalizers.teleport import TeleportNormalizer
from warlock.normalizers.tenable import TenableNormalizer
from warlock.normalizers.thoropass import ThoropassNormalizer
from warlock.normalizers.three60learning import Three60LearningNormalizer
from warlock.normalizers.traceable_ai import TraceableAINormalizer
from warlock.normalizers.transcend import TranscendNormalizer
from warlock.normalizers.trello import TrelloNormalizer
from warlock.normalizers.trinet import TriNetNormalizer
from warlock.normalizers.trustarc import TrustArcNormalizer
from warlock.normalizers.twilio import TwilioNormalizer
from warlock.normalizers.twingate import TwingateNormalizer
from warlock.normalizers.udemy import UdemyNormalizer
from warlock.normalizers.ukg import UKGNormalizer
from warlock.normalizers.upwind import UpwindNormalizer
from warlock.normalizers.vanta import VantaNormalizer
from warlock.normalizers.vanta_api import VantaApiNormalizer
from warlock.normalizers.vantage_finops import VantageFinOpsNormalizer
from warlock.normalizers.varonis import VaronisNormalizer
from warlock.normalizers.vault import VaultNormalizer
from warlock.normalizers.veeam import VeeamNormalizer
from warlock.normalizers.venafi import VenafiNormalizer
from warlock.normalizers.vendr import VendrNormalizer
from warlock.normalizers.vercel_cloud import VercelCloudNormalizer
from warlock.normalizers.verkada import VerkadaNormalizer
from warlock.normalizers.vertex_ai import VertexAINormalizer
from warlock.normalizers.vulcan import VulcanNormalizer
from warlock.normalizers.wallarm import WallarmNormalizer
from warlock.normalizers.wandb import WandbNormalizer
from warlock.normalizers.webex import WebexNormalizer
from warlock.normalizers.webflow import WebflowNormalizer
from warlock.normalizers.wiz import WizNormalizer
from warlock.normalizers.wiz_code import WizCodeNormalizer
from warlock.normalizers.workable import WorkableNormalizer
from warlock.normalizers.workday import WorkdayNormalizer
from warlock.normalizers.workspace_one import WorkspaceOneNormalizer
from warlock.normalizers.wrike import WrikeNormalizer
from warlock.normalizers.xero_payroll import XeroPayrollNormalizer
from warlock.normalizers.zendesk import ZendeskNormalizer
from warlock.normalizers.zentry import ZentryNormalizer
from warlock.normalizers.zoho_desk import ZohoDeskNormalizer
from warlock.normalizers.zoho_people import ZohoPeopleNormalizer
from warlock.normalizers.zoom import ZoomNormalizer
from warlock.normalizers.zscaler import ZscalerNormalizer
