"""add POAM, CompensatingControl, RiskAcceptance models and Issue.poam_id

Revision ID: 07e3655715b0
Revises: 884163ba4d5a
Create Date: 2026-03-19 08:38:31.367362

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07e3655715b0"
down_revision: Union[str, Sequence[str], None] = "884163ba4d5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "poams",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("finding_id", sa.String(length=36), nullable=True),
        sa.Column("control_result_id", sa.String(length=36), nullable=True),
        sa.Column("framework", sa.String(length=50), nullable=False),
        sa.Column("control_id", sa.String(length=50), nullable=False),
        sa.Column("system_profile_id", sa.String(length=36), nullable=True),
        sa.Column("weakness_description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("risk_level", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("milestones", sqlite.JSON(), nullable=True),
        sa.Column("scheduled_completion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_completion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delay_count", sa.Integer(), nullable=True),
        sa.Column("delay_justifications", sqlite.JSON(), nullable=True),
        sa.Column("resources_required", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("vendor_dependency", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["control_result_id"],
            ["control_results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["system_profile_id"],
            ["system_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("poams", schema=None) as batch_op:
        batch_op.create_index("idx_poam_completion", ["scheduled_completion"], unique=False)
        batch_op.create_index("idx_poam_framework", ["framework", "control_id"], unique=False)
        batch_op.create_index("idx_poam_status", ["status"], unique=False)
        batch_op.create_index("idx_poam_system", ["system_profile_id"], unique=False)

    op.create_table(
        "compensating_controls",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("original_framework", sa.String(length=50), nullable=False),
        sa.Column("original_control_id", sa.String(length=50), nullable=False),
        sa.Column("poam_id", sa.String(length=36), nullable=True),
        sa.Column("system_profile_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("implementation_details", sa.Text(), nullable=True),
        sa.Column("evidence_references", sqlite.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expiry_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_frequency", sa.String(length=20), nullable=True),
        sa.Column("last_reviewed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effectiveness_score", sa.Float(), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["poam_id"],
            ["poams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["system_profile_id"],
            ["system_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("compensating_controls", schema=None) as batch_op:
        batch_op.create_index(
            "idx_cc_control", ["original_framework", "original_control_id"], unique=False
        )
        batch_op.create_index("idx_cc_status", ["status"], unique=False)

    op.create_table(
        "risk_acceptances",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("framework", sa.String(length=50), nullable=False),
        sa.Column("control_id", sa.String(length=50), nullable=False),
        sa.Column("poam_id", sa.String(length=36), nullable=True),
        sa.Column("system_profile_id", sa.String(length=36), nullable=True),
        sa.Column("risk_description", sa.Text(), nullable=False),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("residual_risk_level", sa.String(length=20), nullable=True),
        sa.Column("conditions", sqlite.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("requested_by", sa.String(length=255), nullable=False),
        sa.Column("reviewed_by", sa.String(length=255), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expiry_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("auto_reeval_triggers", sqlite.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["poam_id"],
            ["poams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["system_profile_id"],
            ["system_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("risk_acceptances", schema=None) as batch_op:
        batch_op.create_index("idx_ra_control", ["framework", "control_id"], unique=False)
        batch_op.create_index("idx_ra_expiry", ["expiry_date"], unique=False)
        batch_op.create_index("idx_ra_status", ["status"], unique=False)

    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.add_column(sa.Column("poam_id", sa.String(length=36), nullable=True))
        batch_op.create_foreign_key("fk_issues_poam_id", "poams", ["poam_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.drop_constraint("fk_issues_poam_id", type_="foreignkey")
        batch_op.drop_column("poam_id")

    with op.batch_alter_table("risk_acceptances", schema=None) as batch_op:
        batch_op.drop_index("idx_ra_status")
        batch_op.drop_index("idx_ra_expiry")
        batch_op.drop_index("idx_ra_control")

    op.drop_table("risk_acceptances")
    with op.batch_alter_table("compensating_controls", schema=None) as batch_op:
        batch_op.drop_index("idx_cc_status")
        batch_op.drop_index("idx_cc_control")

    op.drop_table("compensating_controls")
    with op.batch_alter_table("poams", schema=None) as batch_op:
        batch_op.drop_index("idx_poam_system")
        batch_op.drop_index("idx_poam_status")
        batch_op.drop_index("idx_poam_framework")
        batch_op.drop_index("idx_poam_completion")

    op.drop_table("poams")
    # ### end Alembic commands ###
