"""add Phase 3-5 models and column additions

Revision ID: 4b0bb472cb63
Revises: 07e3655715b0
Create Date: 2026-03-19 08:41:04.009959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4b0bb472cb63'
down_revision: Union[str, Sequence[str], None] = '07e3655715b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('detail', sqlite.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.create_index('idx_ce_occurred', ['occurred_at'], unique=False)
        batch_op.create_index('idx_ce_resource', ['resource_id'], unique=False)
        batch_op.create_index('idx_ce_sha256', ['sha256'], unique=False)
        batch_op.create_index('idx_ce_source', ['source', 'source_type'], unique=False)

    op.create_table('external_auditors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('firm', sa.String(length=255), nullable=True),
    sa.Column('magic_link_hash', sa.String(length=64), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('policy_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('policy_rego', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditor_engagement_assignments',
    sa.Column('auditor_id', sa.String(length=36), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['external_auditors.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['audit_engagements.id'], ),
    sa.PrimaryKeyConstraint('auditor_id', 'engagement_id')
    )
    op.create_table('compliance_drifts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('control_id', sa.String(length=50), nullable=False),
    sa.Column('system_profile_id', sa.String(length=36), nullable=True),
    sa.Column('previous_status', sa.String(length=20), nullable=False),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('drift_direction', sa.String(length=20), nullable=False),
    sa.Column('previous_posture_score', sa.Float(), nullable=True),
    sa.Column('new_posture_score', sa.Float(), nullable=True),
    sa.Column('correlated_change_event_ids', sqlite.JSON(), nullable=True),
    sa.Column('root_cause_summary', sa.Text(), nullable=True),
    sa.Column('correlation_confidence', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['system_profile_id'], ['system_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_drifts', schema=None) as batch_op:
        batch_op.create_index('idx_drift_control', ['framework', 'control_id'], unique=False)
        batch_op.create_index('idx_drift_detected', ['detected_at'], unique=False)
        batch_op.create_index('idx_drift_direction', ['drift_direction'], unique=False)

    op.create_table('control_inheritances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('system_profile_id', sa.String(length=36), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('control_id', sa.String(length=50), nullable=False),
    sa.Column('inheritance_type', sa.String(length=20), nullable=False),
    sa.Column('provider_system_id', sa.String(length=36), nullable=True),
    sa.Column('provider_description', sa.Text(), nullable=True),
    sa.Column('responsibility_description', sa.Text(), nullable=True),
    sa.Column('evidence_requirement', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_system_id'], ['system_profiles.id'], ),
    sa.ForeignKeyConstraint(['system_profile_id'], ['system_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('control_inheritances', schema=None) as batch_op:
        batch_op.create_index('idx_ci_provider', ['provider_system_id'], unique=False)
        batch_op.create_index('idx_ci_system_control', ['system_profile_id', 'framework', 'control_id'], unique=True)

    op.create_table('evidence_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('auditor_id', sa.String(length=36), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=True),
    sa.Column('control_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('fulfilled_by', sa.String(length=255), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfillment_notes', sa.Text(), nullable=True),
    sa.Column('evidence_ids', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['external_auditors.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['audit_engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('consumer_system_id', sa.String(length=36), nullable=False),
    sa.Column('provider_system_id', sa.String(length=36), nullable=False),
    sa.Column('shared_controls', sqlite.JSON(), nullable=True),
    sa.Column('dependency_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consumer_system_id'], ['system_profiles.id'], ),
    sa.ForeignKeyConstraint(['provider_system_id'], ['system_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_dependencies', schema=None) as batch_op:
        batch_op.create_index('idx_sd_consumer', ['consumer_system_id'], unique=False)
        batch_op.create_index('idx_sd_provider', ['provider_system_id'], unique=False)

    with op.batch_alter_table('audit_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_auditor_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_audit_comments_auditor', 'external_auditors', ['external_auditor_id'], ['id'])

    with op.batch_alter_table('control_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_profile_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('examined_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('examined_by', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key('fk_control_results_system', 'system_profiles', ['system_profile_id'], ['id'])

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_profile_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_findings_system', 'system_profiles', ['system_profile_id'], ['id'])

    with op.batch_alter_table('posture_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_profile_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('uptime_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mttr_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('drift_count', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_posture_snapshots_system', 'system_profiles', ['system_profile_id'], ['id'])

    with op.batch_alter_table('system_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retention_policy_days', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_control_families', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('allowed_actions', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('allowed_actions')
        batch_op.drop_column('allowed_control_families')

    with op.batch_alter_table('system_profiles', schema=None) as batch_op:
        batch_op.drop_column('retention_policy_days')

    with op.batch_alter_table('posture_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posture_snapshots_system', type_='foreignkey')
        batch_op.drop_column('drift_count')
        batch_op.drop_column('mttr_hours')
        batch_op.drop_column('uptime_pct')
        batch_op.drop_column('system_profile_id')

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_findings_system', type_='foreignkey')
        batch_op.drop_column('system_profile_id')

    with op.batch_alter_table('control_results', schema=None) as batch_op:
        batch_op.drop_constraint('fk_control_results_system', type_='foreignkey')
        batch_op.drop_column('examined_by')
        batch_op.drop_column('examined_at')
        batch_op.drop_column('system_profile_id')

    with op.batch_alter_table('audit_comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audit_comments_auditor', type_='foreignkey')
        batch_op.drop_column('external_auditor_id')

    with op.batch_alter_table('system_dependencies', schema=None) as batch_op:
        batch_op.drop_index('idx_sd_provider')
        batch_op.drop_index('idx_sd_consumer')

    op.drop_table('system_dependencies')
    op.drop_table('evidence_requests')
    with op.batch_alter_table('control_inheritances', schema=None) as batch_op:
        batch_op.drop_index('idx_ci_system_control')
        batch_op.drop_index('idx_ci_provider')

    op.drop_table('control_inheritances')
    with op.batch_alter_table('compliance_drifts', schema=None) as batch_op:
        batch_op.drop_index('idx_drift_direction')
        batch_op.drop_index('idx_drift_detected')
        batch_op.drop_index('idx_drift_control')

    op.drop_table('compliance_drifts')
    op.drop_table('auditor_engagement_assignments')
    op.drop_table('policy_overrides')
    op.drop_table('external_auditors')
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.drop_index('idx_ce_source')
        batch_op.drop_index('idx_ce_sha256')
        batch_op.drop_index('idx_ce_resource')
        batch_op.drop_index('idx_ce_occurred')

    op.drop_table('change_events')
    # ### end Alembic commands ###
