"""initial schema baseline

Revision ID: 735d585d425d
Revises:
Create Date: 2026-03-19 08:24:37.284745

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "735d585d425d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_engagements",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("framework", sa.String(length=50), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("in_scope_controls", sqlite.JSON(), nullable=True),
        sa.Column("excluded_controls", sqlite.JSON(), nullable=True),
        sa.Column("auditor_name", sa.String(length=255), nullable=True),
        sa.Column("auditor_firm", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_engagements", schema=None) as batch_op:
        batch_op.create_index("idx_engagement_framework", ["framework"], unique=False)
        batch_op.create_index("idx_engagement_period", ["period_start", "period_end"], unique=False)
        batch_op.create_index("idx_engagement_status", ["status"], unique=False)

    op.create_table(
        "audit_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("previous_hash", sa.String(length=64), nullable=False),
        sa.Column("entry_hash", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("evidence_sha256", sa.String(length=64), nullable=True),
        sa.Column("metadata", sqlite.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_entries", schema=None) as batch_op:
        batch_op.create_index("idx_audit_action", ["action"], unique=False)
        batch_op.create_index("idx_audit_created", ["created_at"], unique=False)
        batch_op.create_index("idx_audit_entity", ["entity_type", "entity_id"], unique=False)
        batch_op.create_index("idx_audit_sequence", ["sequence"], unique=False)

    op.create_table(
        "connector_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("connector_name", sa.String(length=100), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("event_count", sa.Integer(), nullable=True),
        sa.Column("error_count", sa.Integer(), nullable=True),
        sa.Column("errors", sqlite.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_silos",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("silo_type", sa.String(length=30), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("data_classification", sa.String(length=20), nullable=True),
        sa.Column("contains_pii", sa.Boolean(), nullable=True),
        sa.Column("contains_phi", sa.Boolean(), nullable=True),
        sa.Column("contains_pci", sa.Boolean(), nullable=True),
        sa.Column("contains_credentials", sa.Boolean(), nullable=True),
        sa.Column("last_scan_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scan_status", sa.String(length=20), nullable=True),
        sa.Column("sensitive_field_count", sa.Integer(), nullable=True),
        sa.Column("total_records", sa.Integer(), nullable=True),
        sa.Column("scan_findings", sqlite.JSON(), nullable=True),
        sa.Column("encrypted_at_rest", sa.Boolean(), nullable=True),
        sa.Column("encrypted_in_transit", sa.Boolean(), nullable=True),
        sa.Column("access_logging_enabled", sa.Boolean(), nullable=True),
        sa.Column("backup_enabled", sa.Boolean(), nullable=True),
        sa.Column("retention_days", sa.Integer(), nullable=True),
        sa.Column("owner", sa.String(length=255), nullable=True),
        sa.Column("team", sa.String(length=100), nullable=True),
        sa.Column("applicable_frameworks", sqlite.JSON(), nullable=True),
        sa.Column("remediation_status", sa.String(length=20), nullable=True),
        sa.Column("remediation_notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("data_silos", schema=None) as batch_op:
        batch_op.create_index("idx_silo_classification", ["data_classification"], unique=False)
        batch_op.create_index("idx_silo_pii", ["contains_pii"], unique=False)
        batch_op.create_index("idx_silo_provider", ["provider"], unique=False)
        batch_op.create_index("idx_silo_type", ["silo_type"], unique=False)

    op.create_table(
        "legal_holds",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("legal_holds", schema=None) as batch_op:
        batch_op.create_index("idx_legal_hold_active", ["is_active"], unique=False)
        batch_op.create_index("idx_legal_hold_dates", ["start_date", "end_date"], unique=False)

    op.create_table(
        "personnel",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("manager_email", sa.String(length=255), nullable=True),
        sa.Column("employee_type", sa.String(length=30), nullable=True),
        sa.Column("hr_employee_id", sa.String(length=100), nullable=True),
        sa.Column("hire_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("termination_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hr_status", sa.String(length=30), nullable=True),
        sa.Column("background_check_status", sa.String(length=30), nullable=True),
        sa.Column("background_check_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("agreements_signed", sqlite.JSON(), nullable=True),
        sa.Column("idp_user_id", sa.String(length=255), nullable=True),
        sa.Column("idp_provider", sa.String(length=30), nullable=True),
        sa.Column("idp_status", sa.String(length=30), nullable=True),
        sa.Column("idp_last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=True),
        sa.Column("idp_groups", sqlite.JSON(), nullable=True),
        sa.Column("training_status", sa.String(length=30), nullable=True),
        sa.Column("last_training_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("phishing_score", sa.Float(), nullable=True),
        sa.Column("training_completions", sqlite.JSON(), nullable=True),
        sa.Column("last_access_review", sa.DateTime(timezone=True), nullable=True),
        sa.Column("access_review_status", sa.String(length=30), nullable=True),
        sa.Column("flags", sqlite.JSON(), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("last_synced", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    with op.batch_alter_table("personnel", schema=None) as batch_op:
        batch_op.create_index("idx_personnel_dept", ["department"], unique=False)
        batch_op.create_index("idx_personnel_email", ["email"], unique=False)
        batch_op.create_index("idx_personnel_flags", ["risk_score"], unique=False)
        batch_op.create_index("idx_personnel_status", ["hr_status"], unique=False)

    op.create_table(
        "posture_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("framework", sa.String(length=50), nullable=False),
        sa.Column("control_id", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("posture_score", sa.Float(), nullable=False),
        sa.Column("total_findings", sa.Integer(), nullable=True),
        sa.Column("compliant_findings", sa.Integer(), nullable=True),
        sa.Column("non_compliant_findings", sa.Integer(), nullable=True),
        sa.Column("partial_findings", sa.Integer(), nullable=True),
        sa.Column("not_assessed_findings", sa.Integer(), nullable=True),
        sa.Column("evidence_sources", sqlite.JSON(), nullable=True),
        sa.Column("evidence_freshness_hours", sa.Float(), nullable=True),
        sa.Column("sufficiency_score", sa.Float(), nullable=True),
        sa.Column("sufficiency_details", sqlite.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("posture_snapshots", schema=None) as batch_op:
        batch_op.create_index("idx_posture_date", ["snapshot_date"], unique=False)
        batch_op.create_index("idx_posture_framework", ["framework", "control_id"], unique=False)
        batch_op.create_index("idx_posture_status", ["status"], unique=False)

    op.create_table(
        "questionnaire_templates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("template_type", sa.String(length=30), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("questions", sqlite.JSON(), nullable=False),
        sa.Column("total_questions", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("questionnaire_templates", schema=None) as batch_op:
        batch_op.create_index("idx_template_type", ["template_type"], unique=False)

    op.create_table(
        "risk_analyses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("framework", sa.String(length=50), nullable=False),
        sa.Column("scenario_name", sa.String(length=255), nullable=False),
        sa.Column("mean_ale", sa.Float(), nullable=False),
        sa.Column("var_95", sa.Float(), nullable=False),
        sa.Column("var_99", sa.Float(), nullable=False),
        sa.Column("control_effectiveness", sa.Float(), nullable=True),
        sa.Column("iterations", sa.Integer(), nullable=True),
        sa.Column("details", sqlite.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("risk_analyses", schema=None) as batch_op:
        batch_op.create_index("idx_risk_created", ["created_at"], unique=False)
        batch_op.create_index("idx_risk_framework", ["framework"], unique=False)

    op.create_table(
        "system_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("acronym", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("confidentiality_impact", sa.String(length=10), nullable=True),
        sa.Column("integrity_impact", sa.String(length=10), nullable=True),
        sa.Column("availability_impact", sa.String(length=10), nullable=True),
        sa.Column("overall_impact", sa.String(length=10), nullable=True),
        sa.Column("cloud_accounts", sqlite.JSON(), nullable=True),
        sa.Column("network_boundaries", sqlite.JSON(), nullable=True),
        sa.Column("interconnections", sqlite.JSON(), nullable=True),
        sa.Column("connector_scope", sqlite.JSON(), nullable=True),
        sa.Column("frameworks", sqlite.JSON(), nullable=True),
        sa.Column("system_owner", sa.String(length=255), nullable=True),
        sa.Column("system_owner_email", sa.String(length=255), nullable=True),
        sa.Column("isso", sa.String(length=255), nullable=True),
        sa.Column("isso_email", sa.String(length=255), nullable=True),
        sa.Column("issm", sa.String(length=255), nullable=True),
        sa.Column("issm_email", sa.String(length=255), nullable=True),
        sa.Column("authorizing_official", sa.String(length=255), nullable=True),
        sa.Column("ao_email", sa.String(length=255), nullable=True),
        sa.Column("authorization_status", sa.String(length=30), nullable=True),
        sa.Column("authorization_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("authorization_expiry", sa.DateTime(timezone=True), nullable=True),
        sa.Column("continuous_monitoring_plan", sa.Text(), nullable=True),
        sa.Column("deployment_model", sa.String(length=30), nullable=True),
        sa.Column("service_model", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("system_profiles", schema=None) as batch_op:
        batch_op.create_index("idx_system_name", ["name"], unique=False)
        batch_op.create_index("idx_system_status", ["authorization_status"], unique=False)

    op.create_table(
        "trust_access_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("contact_name", sa.String(length=255), nullable=False),
        sa.Column("contact_email", sa.String(length=255), nullable=False),
        sa.Column("document_types", sqlite.JSON(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("nda_accepted", sa.Boolean(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reviewed_by", sa.String(length=255), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("trust_access_requests", schema=None) as batch_op:
        batch_op.create_index("idx_trust_req_email", ["contact_email"], unique=False)
        batch_op.create_index("idx_trust_req_status", ["status"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("allowed_frameworks", sqlite.JSON(), nullable=True),
        sa.Column("allowed_sources", sqlite.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("idx_user_email", ["email"], unique=False)
        batch_op.create_index("idx_user_role", ["role"], unique=False)

    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("scopes", sqlite.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index("idx_apikey_hash", ["key_hash"], unique=False)
        batch_op.create_index("idx_apikey_user", ["user_id"], unique=False)

    op.create_table(
        "attestations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("engagement_id", sa.String(length=36), nullable=True),
        sa.Column("framework", sa.String(length=50), nullable=False),
        sa.Column("control_id", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("evidence_references", sqlite.JSON(), nullable=True),
        sa.Column("prepared_by", sa.String(length=255), nullable=True),
        sa.Column("prepared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_by", sa.String(length=255), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.String(length=255), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_by", sa.String(length=255), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["audit_engagements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("attestations", schema=None) as batch_op:
        batch_op.create_index("idx_attest_engagement", ["engagement_id"], unique=False)
        batch_op.create_index("idx_attest_framework", ["framework", "control_id"], unique=False)
        batch_op.create_index("idx_attest_status", ["status"], unique=False)

    op.create_table(
        "audit_comments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("engagement_id", sa.String(length=36), nullable=False),
        sa.Column("target_type", sa.String(length=30), nullable=False),
        sa.Column("target_id", sa.String(length=50), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("author_role", sa.String(length=20), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=True),
        sa.Column("resolved_by", sa.String(length=255), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["audit_engagements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_comments", schema=None) as batch_op:
        batch_op.create_index("idx_auditcomment_engagement", ["engagement_id"], unique=False)
        batch_op.create_index("idx_auditcomment_target", ["target_type", "target_id"], unique=False)

    op.create_table(
        "questionnaires",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("template_id", sa.String(length=36), nullable=False),
        sa.Column("vendor_name", sa.String(length=255), nullable=False),
        sa.Column("vendor_contact_email", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("responses", sqlite.JSON(), nullable=True),
        sa.Column("completion_pct", sa.Float(), nullable=True),
        sa.Column("ai_suggested_answers", sqlite.JSON(), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("risk_findings", sqlite.JSON(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.String(length=255), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["questionnaire_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("questionnaires", schema=None) as batch_op:
        batch_op.create_index("idx_questionnaire_status", ["status"], unique=False)
        batch_op.create_index("idx_questionnaire_template", ["template_id"], unique=False)
        batch_op.create_index("idx_questionnaire_vendor", ["vendor_name"], unique=False)

    op.create_table(
        "raw_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("connector_run_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("raw_data", sqlite.JSON(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connector_run_id"],
            ["connector_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("raw_events", schema=None) as batch_op:
        batch_op.create_index("idx_raw_ingested", ["ingested_at"], unique=False)
        batch_op.create_index("idx_raw_sha256", ["sha256"], unique=False)
        batch_op.create_index("idx_raw_source", ["source", "provider"], unique=False)

    op.create_table(
        "findings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("raw_event_id", sa.String(length=36), nullable=False),
        sa.Column("observation_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("detail", sqlite.JSON(), nullable=False),
        sa.Column("resource_id", sa.Text(), nullable=True),
        sa.Column("resource_type", sa.String(length=100), nullable=True),
        sa.Column("resource_name", sa.Text(), nullable=True),
        sa.Column("account_id", sa.String(length=100), nullable=True),
        sa.Column("region", sa.String(length=50), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["raw_event_id"],
            ["raw_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.create_index("idx_finding_observed", ["observed_at"], unique=False)
        batch_op.create_index(
            "idx_finding_resource", ["resource_type", "resource_id"], unique=False
        )
        batch_op.create_index("idx_finding_severity", ["severity"], unique=False)
        batch_op.create_index("idx_finding_source", ["source", "provider"], unique=False)
        batch_op.create_index("idx_finding_type", ["observation_type"], unique=False)

    op.create_table(
        "control_mappings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("finding_id", sa.String(length=36), nullable=False),
        sa.Column("framework", sa.String(length=50), nullable=False),
        sa.Column("control_id", sa.String(length=50), nullable=False),
        sa.Column("control_family", sa.String(length=50), nullable=True),
        sa.Column("mapping_method", sa.String(length=30), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("crosswalk_path", sqlite.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("control_mappings", schema=None) as batch_op:
        batch_op.create_index("idx_mapping_control", ["framework", "control_id"], unique=False)
        batch_op.create_index("idx_mapping_finding", ["finding_id"], unique=False)

    op.create_table(
        "control_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("finding_id", sa.String(length=36), nullable=False),
        sa.Column("control_mapping_id", sa.String(length=36), nullable=False),
        sa.Column("framework", sa.String(length=50), nullable=False),
        sa.Column("control_id", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("assertion_name", sa.String(length=100), nullable=True),
        sa.Column("assertion_passed", sa.Boolean(), nullable=True),
        sa.Column("assertion_findings", sqlite.JSON(), nullable=True),
        sa.Column("ai_assessment", sa.Text(), nullable=True),
        sa.Column("ai_confidence", sa.Float(), nullable=True),
        sa.Column("ai_model", sa.String(length=50), nullable=True),
        sa.Column("remediation_summary", sa.Text(), nullable=True),
        sa.Column("remediation_steps", sqlite.JSON(), nullable=True),
        sa.Column("console_path", sa.Text(), nullable=True),
        sa.Column("evidence_ids", sqlite.JSON(), nullable=True),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assessor", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["control_mapping_id"],
            ["control_mappings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("control_results", schema=None) as batch_op:
        batch_op.create_index("idx_result_assessed", ["assessed_at"], unique=False)
        batch_op.create_index("idx_result_control", ["framework", "control_id"], unique=False)
        batch_op.create_index("idx_result_finding", ["finding_id"], unique=False)
        batch_op.create_index("idx_result_status", ["status"], unique=False)

    op.create_table(
        "issues",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("finding_id", sa.String(length=36), nullable=True),
        sa.Column("control_result_id", sa.String(length=36), nullable=True),
        sa.Column("framework", sa.String(length=50), nullable=True),
        sa.Column("control_id", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("assigned_to", sa.String(length=255), nullable=True),
        sa.Column("assigned_by", sa.String(length=255), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remediated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("risk_accepted", sa.Boolean(), nullable=True),
        sa.Column("risk_acceptance_owner", sa.String(length=255), nullable=True),
        sa.Column("risk_acceptance_expiry", sa.DateTime(timezone=True), nullable=True),
        sa.Column("risk_acceptance_justification", sa.Text(), nullable=True),
        sa.Column("remediation_plan", sa.Text(), nullable=True),
        sa.Column("remediation_evidence", sqlite.JSON(), nullable=True),
        sa.Column("verification_notes", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("tags", sqlite.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["control_result_id"],
            ["control_results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.create_index("idx_issue_assigned", ["assigned_to"], unique=False)
        batch_op.create_index("idx_issue_due", ["due_date"], unique=False)
        batch_op.create_index("idx_issue_framework", ["framework", "control_id"], unique=False)
        batch_op.create_index("idx_issue_priority", ["priority"], unique=False)
        batch_op.create_index("idx_issue_status", ["status"], unique=False)

    op.create_table(
        "issue_comments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("issue_id", sa.String(length=36), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("comment_type", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("issue_comments", schema=None) as batch_op:
        batch_op.create_index("idx_comment_issue", ["issue_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issue_comments", schema=None) as batch_op:
        batch_op.drop_index("idx_comment_issue")

    op.drop_table("issue_comments")
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.drop_index("idx_issue_status")
        batch_op.drop_index("idx_issue_priority")
        batch_op.drop_index("idx_issue_framework")
        batch_op.drop_index("idx_issue_due")
        batch_op.drop_index("idx_issue_assigned")

    op.drop_table("issues")
    with op.batch_alter_table("control_results", schema=None) as batch_op:
        batch_op.drop_index("idx_result_status")
        batch_op.drop_index("idx_result_finding")
        batch_op.drop_index("idx_result_control")
        batch_op.drop_index("idx_result_assessed")

    op.drop_table("control_results")
    with op.batch_alter_table("control_mappings", schema=None) as batch_op:
        batch_op.drop_index("idx_mapping_finding")
        batch_op.drop_index("idx_mapping_control")

    op.drop_table("control_mappings")
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.drop_index("idx_finding_type")
        batch_op.drop_index("idx_finding_source")
        batch_op.drop_index("idx_finding_severity")
        batch_op.drop_index("idx_finding_resource")
        batch_op.drop_index("idx_finding_observed")

    op.drop_table("findings")
    with op.batch_alter_table("raw_events", schema=None) as batch_op:
        batch_op.drop_index("idx_raw_source")
        batch_op.drop_index("idx_raw_sha256")
        batch_op.drop_index("idx_raw_ingested")

    op.drop_table("raw_events")
    with op.batch_alter_table("questionnaires", schema=None) as batch_op:
        batch_op.drop_index("idx_questionnaire_vendor")
        batch_op.drop_index("idx_questionnaire_template")
        batch_op.drop_index("idx_questionnaire_status")

    op.drop_table("questionnaires")
    with op.batch_alter_table("audit_comments", schema=None) as batch_op:
        batch_op.drop_index("idx_auditcomment_target")
        batch_op.drop_index("idx_auditcomment_engagement")

    op.drop_table("audit_comments")
    with op.batch_alter_table("attestations", schema=None) as batch_op:
        batch_op.drop_index("idx_attest_status")
        batch_op.drop_index("idx_attest_framework")
        batch_op.drop_index("idx_attest_engagement")

    op.drop_table("attestations")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index("idx_apikey_user")
        batch_op.drop_index("idx_apikey_hash")

    op.drop_table("api_keys")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("idx_user_role")
        batch_op.drop_index("idx_user_email")

    op.drop_table("users")
    with op.batch_alter_table("trust_access_requests", schema=None) as batch_op:
        batch_op.drop_index("idx_trust_req_status")
        batch_op.drop_index("idx_trust_req_email")

    op.drop_table("trust_access_requests")
    with op.batch_alter_table("system_profiles", schema=None) as batch_op:
        batch_op.drop_index("idx_system_status")
        batch_op.drop_index("idx_system_name")

    op.drop_table("system_profiles")
    with op.batch_alter_table("risk_analyses", schema=None) as batch_op:
        batch_op.drop_index("idx_risk_framework")
        batch_op.drop_index("idx_risk_created")

    op.drop_table("risk_analyses")
    with op.batch_alter_table("questionnaire_templates", schema=None) as batch_op:
        batch_op.drop_index("idx_template_type")

    op.drop_table("questionnaire_templates")
    with op.batch_alter_table("posture_snapshots", schema=None) as batch_op:
        batch_op.drop_index("idx_posture_status")
        batch_op.drop_index("idx_posture_framework")
        batch_op.drop_index("idx_posture_date")

    op.drop_table("posture_snapshots")
    with op.batch_alter_table("personnel", schema=None) as batch_op:
        batch_op.drop_index("idx_personnel_status")
        batch_op.drop_index("idx_personnel_flags")
        batch_op.drop_index("idx_personnel_email")
        batch_op.drop_index("idx_personnel_dept")

    op.drop_table("personnel")
    with op.batch_alter_table("legal_holds", schema=None) as batch_op:
        batch_op.drop_index("idx_legal_hold_dates")
        batch_op.drop_index("idx_legal_hold_active")

    op.drop_table("legal_holds")
    with op.batch_alter_table("data_silos", schema=None) as batch_op:
        batch_op.drop_index("idx_silo_type")
        batch_op.drop_index("idx_silo_provider")
        batch_op.drop_index("idx_silo_pii")
        batch_op.drop_index("idx_silo_classification")

    op.drop_table("data_silos")
    op.drop_table("connector_runs")
    with op.batch_alter_table("audit_entries", schema=None) as batch_op:
        batch_op.drop_index("idx_audit_sequence")
        batch_op.drop_index("idx_audit_entity")
        batch_op.drop_index("idx_audit_created")
        batch_op.drop_index("idx_audit_action")

    op.drop_table("audit_entries")
    with op.batch_alter_table("audit_engagements", schema=None) as batch_op:
        batch_op.drop_index("idx_engagement_status")
        batch_op.drop_index("idx_engagement_period")
        batch_op.drop_index("idx_engagement_framework")

    op.drop_table("audit_engagements")
    # ### end Alembic commands ###
