"""add monitoring_frequency to control_mappings

Revision ID: 884163ba4d5a
Revises: 735d585d425d
Create Date: 2026-03-19 08:25:05.013534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '884163ba4d5a'
down_revision: Union[str, Sequence[str], None] = '735d585d425d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('control_mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitoring_frequency', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('control_mappings', schema=None) as batch_op:
        batch_op.drop_column('monitoring_frequency')

    # ### end Alembic commands ###
