"""Alert rules engine -- generates alerts from pipeline data.

Evaluates registered rules against the database and creates Alert objects
when conditions are met. Rules are not auto-run during pipeline execution;
they are triggered explicitly via ``warlock alerts evaluate`` or the API.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Callable

from sqlalchemy.orm import Session


@dataclass
class AlertRule:
    """A single alert rule definition.

    Attributes:
        name: Unique rule identifier (snake_case).
        description: Human-readable description of what this rule detects.
        category: One of control_drift, new_finding, connector_failure,
                  threshold_breach, policy_violation.
        severity: Default severity for alerts generated by this rule.
        check: Callable that receives a SQLAlchemy Session and returns a list
               of dicts, each describing one alert payload.
    """

    name: str
    description: str
    category: str
    severity: str  # critical, high, medium, low
    check: Callable[[Session], list[dict]]


def _check_control_drift(session: Session) -> list[dict]:
    """Detect controls that were compliant but are now non_compliant."""
    from sqlalchemy import func

    from warlock.db.models import ControlResult

    # Find controls that have both compliant and non_compliant results,
    # where the latest result is non_compliant.
    subq = (
        session.query(
            ControlResult.framework,
            ControlResult.control_id,
            func.max(ControlResult.assessed_at).label("latest"),
        )
        .group_by(ControlResult.framework, ControlResult.control_id)
        .subquery()
    )

    drifted = (
        session.query(ControlResult)
        .join(
            subq,
            (ControlResult.framework == subq.c.framework)
            & (ControlResult.control_id == subq.c.control_id)
            & (ControlResult.assessed_at == subq.c.latest),
        )
        .filter(ControlResult.status == "non_compliant")
        .all()
    )

    # Only alert if there is also a previous compliant result for the same control
    alerts: list[dict] = []
    seen: set[tuple[str, str]] = set()
    for cr in drifted:
        key = (cr.framework, cr.control_id)
        if key in seen:
            continue
        prev_compliant = (
            session.query(ControlResult)
            .filter(
                ControlResult.framework == cr.framework,
                ControlResult.control_id == cr.control_id,
                ControlResult.status == "compliant",
                ControlResult.id != cr.id,
            )
            .first()
        )
        if prev_compliant:
            seen.add(key)
            alerts.append(
                {
                    "title": f"Control drift: {cr.framework} {cr.control_id} regressed to non_compliant",
                    "description": (
                        f"Control {cr.control_id} in {cr.framework} was previously compliant "
                        f"but the latest assessment is non_compliant."
                    ),
                    "framework": cr.framework,
                    "control_id": cr.control_id,
                    "control_result_id": cr.id,
                }
            )
    return alerts


def _check_critical_findings(session: Session) -> list[dict]:
    """Detect any findings with severity=critical."""
    from warlock.db.models import Alert, Finding

    # Only alert for findings not already linked to an existing alert
    existing_finding_ids = {
        row[0] for row in session.query(Alert.finding_id).filter(Alert.finding_id.isnot(None)).all()
    }

    findings = session.query(Finding).filter(Finding.severity == "critical").all()
    alerts: list[dict] = []
    for f in findings:
        if f.id not in existing_finding_ids:
            alerts.append(
                {
                    "title": f"Critical finding: {f.title[:120]}",
                    "description": f"Critical severity finding detected: {f.title}",
                    "finding_id": f.id,
                }
            )
    return alerts


def _check_connector_failures(session: Session) -> list[dict]:
    """Detect ConnectorRun records with status=error."""
    from warlock.db.models import Alert, ConnectorRun

    existing_connector_names = {
        row[0]
        for row in session.query(Alert.connector_name)
        .filter(
            Alert.connector_name.isnot(None),
            Alert.category == "connector_failure",
            Alert.status == "open",
        )
        .all()
    }

    runs = session.query(ConnectorRun).filter(ConnectorRun.status == "error").all()
    alerts: list[dict] = []
    for run in runs:
        if run.connector_name not in existing_connector_names:
            alerts.append(
                {
                    "title": f"Connector failure: {run.connector_name}",
                    "description": (
                        f"Connector {run.connector_name} failed with {run.error_count} error(s)."
                    ),
                    "connector_name": run.connector_name,
                }
            )
    return alerts


def _check_high_non_compliance(session: Session) -> list[dict]:
    """Detect frameworks with >50% non_compliant controls."""
    from sqlalchemy import func

    from warlock.db.models import ControlResult

    # Get latest result per (framework, control_id) using a subquery
    subq = (
        session.query(
            ControlResult.framework,
            ControlResult.control_id,
            func.max(ControlResult.assessed_at).label("latest"),
        )
        .group_by(ControlResult.framework, ControlResult.control_id)
        .subquery()
    )

    latest_results = (
        session.query(ControlResult)
        .join(
            subq,
            (ControlResult.framework == subq.c.framework)
            & (ControlResult.control_id == subq.c.control_id)
            & (ControlResult.assessed_at == subq.c.latest),
        )
        .all()
    )

    # Group by framework
    fw_stats: dict[str, dict[str, int]] = {}
    for cr in latest_results:
        if cr.framework not in fw_stats:
            fw_stats[cr.framework] = {"total": 0, "non_compliant": 0}
        fw_stats[cr.framework]["total"] += 1
        if cr.status == "non_compliant":
            fw_stats[cr.framework]["non_compliant"] += 1

    alerts: list[dict] = []
    for fw, stats in fw_stats.items():
        if stats["total"] > 0:
            rate = stats["non_compliant"] / stats["total"]
            if rate > 0.50:
                pct = int(rate * 100)
                alerts.append(
                    {
                        "title": f"High non-compliance: {fw} at {pct}%",
                        "description": (
                            f"Framework {fw} has {stats['non_compliant']}/{stats['total']} "
                            f"controls non-compliant ({pct}%)."
                        ),
                        "framework": fw,
                    }
                )
    return alerts


def _check_stale_connectors(session: Session) -> list[dict]:
    """Detect connectors that haven't run in >24 hours."""
    from sqlalchemy import func

    from warlock.db.models import ConnectorRun

    cutoff = datetime.now(timezone.utc) - timedelta(hours=24)

    # Get the latest run per connector
    subq = (
        session.query(
            ConnectorRun.connector_name,
            func.max(ConnectorRun.started_at).label("latest"),
        )
        .group_by(ConnectorRun.connector_name)
        .subquery()
    )

    stale = session.query(subq).filter(subq.c.latest < cutoff).all()
    alerts: list[dict] = []
    for row in stale:
        alerts.append(
            {
                "title": f"Stale connector: {row.connector_name}",
                "description": (
                    f"Connector {row.connector_name} last ran at {row.latest}. "
                    f"No runs in the past 24 hours."
                ),
                "connector_name": row.connector_name,
            }
        )
    return alerts


# ---------------------------------------------------------------------------
# Built-in rules
# ---------------------------------------------------------------------------

BUILTIN_RULES: list[AlertRule] = [
    AlertRule(
        name="control_previously_passing_now_failing",
        description="Control was compliant in a previous run but is now non_compliant",
        category="control_drift",
        severity="high",
        check=_check_control_drift,
    ),
    AlertRule(
        name="critical_finding_detected",
        description="Any finding with severity=critical triggers an alert",
        category="new_finding",
        severity="critical",
        check=_check_critical_findings,
    ),
    AlertRule(
        name="connector_health_failure",
        description="Any ConnectorRun with status=error",
        category="connector_failure",
        severity="high",
        check=_check_connector_failures,
    ),
    AlertRule(
        name="high_non_compliance_rate",
        description="Framework with >50% non_compliant controls",
        category="threshold_breach",
        severity="high",
        check=_check_high_non_compliance,
    ),
    AlertRule(
        name="stale_connector",
        description="Connector hasn't run in >24 hours",
        category="policy_violation",
        severity="medium",
        check=_check_stale_connectors,
    ),
]


# ---------------------------------------------------------------------------
# Engine
# ---------------------------------------------------------------------------


@dataclass
class AlertRulesEngine:
    """Evaluates registered alert rules and creates Alert objects.

    Usage::

        engine = AlertRulesEngine()
        with get_session() as session:
            new_alerts = engine.evaluate(session)
    """

    rules: list[AlertRule] = field(default_factory=lambda: list(BUILTIN_RULES))

    def register(self, rule: AlertRule) -> None:
        """Register a new alert rule."""
        self.rules.append(rule)

    def evaluate(self, session: Session) -> list:
        """Run all registered rules and create Alert objects for matches.

        Returns:
            List of newly created Alert model instances (already added to session).
        """
        import uuid

        from warlock.db.models import Alert

        now = datetime.now(timezone.utc)
        created: list[Alert] = []

        for rule in self.rules:
            try:
                payloads = rule.check(session)
            except Exception:  # noqa: BLE001
                # Rule evaluation failure should not crash the engine
                continue

            for payload in payloads:
                alert = Alert(
                    id=str(uuid.uuid4()),
                    title=payload.get("title", f"Alert from {rule.name}"),
                    description=payload.get("description"),
                    severity=rule.severity,
                    category=rule.category,
                    finding_id=payload.get("finding_id"),
                    control_result_id=payload.get("control_result_id"),
                    connector_name=payload.get("connector_name"),
                    framework=payload.get("framework"),
                    control_id=payload.get("control_id"),
                    status="open",
                    rule_name=rule.name,
                    rule_metadata={"rule_description": rule.description},
                    triggered_at=now,
                    created_at=now,
                )
                session.add(alert)
                created.append(alert)

        if created:
            session.commit()

        return created
